import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import { getContract } from '@/configureWarpClient';

export default function Home() {
  const [resumes, setResumes] = useState([])
  useEffect(() => {
    readState()
  }, [])
  async function readState() {
    const contract = await getContract()
    try {
      const data = await contract.readState()
      console.log('data: ', data)
      const resumes = Object.values(data.cachedValue.state.resumes)
      setResumes(resumes)
      console.log('resumes: ', resumes)
    } catch (err) {
      console.log('error: ', err)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Showing all resumes</h1>

      </main>
    </>
  )
}
